version: "3.8"

services:
  archivy:
    image: uzayg/archivy:v1.3.0
    ports:
      - "5111:5000"
    environment:
      FLASK_DEBUG: 0
      ELASTICSEARCH_ENABLED: 1
      ELASTICSEARCH_URL: "http://elasticsearch:9200/"
      HOST: "kens-mate-002.lan.fyi"
    volumes:
      - ./css:/archivy/css
      - ./data:/archivy/data
      - ./images:/archivy/images
      - ./config:/archivy/.local/share/archivy
  elasticsearch:
    image: elasticsearch:7.12.1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data:rw
    environment:
      - "discovery.type=single-node"

volumes:
  elasticsearch_data:
